"""Faz 1 sema: market, depo, urun, fiyat gecmisi, takip listesi

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-26 19:40:19.204362
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_product_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('refined_volume_or_weight', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('main_category', sa.String(length=200), nullable=True),
    sa.Column('menu_category', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_refined_volume_or_weight'), 'products', ['refined_volume_or_weight'], unique=False)
    op.create_index(op.f('ix_products_source_product_id'), 'products', ['source_product_id'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_market_id'), 'depots', ['market_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_product_id', sa.String(length=32), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_collected_at'), 'raw_records', ['collected_at'], unique=False)
    op.create_index(op.f('ix_raw_records_processed'), 'raw_records', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_records_source'), 'raw_records', ['source'], unique=False)
    op.create_index(op.f('ix_raw_records_source_product_id'), 'raw_records', ['source_product_id'], unique=False)
    op.create_table('watchlist_source_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('source_product_id', sa.String(length=32), nullable=False),
    sa.Column('title_snapshot', sa.String(length=500), nullable=True),
    sa.Column('link_confirmed_by', sa.String(length=20), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.source_product_id'], ),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_source_ids_source_product_id'), 'watchlist_source_ids', ['source_product_id'], unique=True)
    op.create_index(op.f('ix_watchlist_source_ids_watchlist_item_id'), 'watchlist_source_ids', ['watchlist_item_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.String(length=64), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discountless_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('unit_price_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit_price_text', sa.String(length=50), nullable=True),
    sa.Column('index_time', sa.DateTime(), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'depot_id', 'collected_date', name='uq_price_history_urun_depo_gun')
    )
    op.create_index(op.f('ix_price_history_collected_date'), 'price_history', ['collected_date'], unique=False)
    op.create_index(op.f('ix_price_history_depot_id'), 'price_history', ['depot_id'], unique=False)
    op.create_index(op.f('ix_price_history_market_id'), 'price_history', ['market_id'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_market_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_depot_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_collected_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_watchlist_source_ids_watchlist_item_id'), table_name='watchlist_source_ids')
    op.drop_index(op.f('ix_watchlist_source_ids_source_product_id'), table_name='watchlist_source_ids')
    op.drop_table('watchlist_source_ids')
    op.drop_index(op.f('ix_raw_records_source_product_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_source'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_processed'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_collected_at'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_depots_market_id'), table_name='depots')
    op.drop_table('depots')
    op.drop_table('watchlist_items')
    op.drop_table('settings')
    op.drop_index(op.f('ix_products_source_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_refined_volume_or_weight'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
